[tools]
bun = "latest"
deno = "latest"
go = "latest"
node = ["22", "20"]
python = ["3.12", "3.11"]
ruby = "3.3.0"

# npm
## pnpm や yarn は corepack のものを使う (下記設定だけで corepack 管理下の pnpm や yarn が使えるようになる)
"npm:corepack" = "latest"

# pipx
"pipx:awsume" = "latest"
"pipx:hatch" = "latest"
"pipx:poetry" = "latest"


[settings]
asdf = false

always_keep_download = true
always_keep_install = true
experimental = true

python_venv_auto_create = true
python_compile = false

[settings.status]
missing_tools = "always"
show_env = true
